### ISSUE TITLE
Metadata size is 139, but the largest accepted size is -1591738368, recording empty

### ISSUE THREAD

**Issue by agrajaghh** [duplicati/duplicati#2089]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.31
**Operating System:** Win10
**Backend:** File

### Steps to reproduce
- set `--blocksize=1000KB`
- run backup

I also notices a wrong  `EndTime: 01.01.0001 00:00:00`

### debug log
```
DeletedFiles: 0
DeletedFolders: 0
ModifiedFiles: 0
ExaminedFiles: 3
OpenedFiles: 3
AddedFiles: 3
SizeOfModifiedFiles: 0
SizeOfAddedFiles: 118641757
SizeOfExaminedFiles: 118641757
SizeOfOpenedFiles: 118641757
NotProcessedFiles: 0
AddedFolders: 1
TooLargeFiles: 0
FilesWithError: 0
ModifiedFolders: 0
ModifiedSymlinks: 0
AddedSymlinks: 0
DeletedSymlinks: 0
PartialBackup: False
Dryrun: False
MainOperation: Backup
CompactResults: null
DeleteResults:
    DeletedSets: []
    Dryrun: False
    MainOperation: Delete
    CompactResults: null
    VerboseOutput: False
    VerboseErrors: False
    EndTime: 01.01.0001 00:00:00
    BeginTime: 03.11.2016 18:18:34
    Duration: -736270.18:18:34.0479175
    BackendStatistics:
        RemoteCalls: 12
        BytesUploaded: 118697435
        BytesDownloaded: 15462519
        FilesUploaded: 7
        FilesDownloaded: 3
        FilesDeleted: 0
        FoldersCreated: 0
        RetryAttempts: 0
        UnknownFileSize: 0
        UnknownFileCount: 0
        KnownFileCount: 7
        KnownFileSize: 118697435
        LastBackupDate: 03.11.2016 19:18:19
        BackupListCount: 1
        TotalQuotaSpace: 239530405888
        FreeQuotaSpace: 40933560320
        AssignedQuotaSpace: -1
        MainOperation: Backup
        VerboseOutput: False
        VerboseErrors: False
        EndTime: 01.01.0001 00:00:00
        BeginTime: 03.11.2016 18:18:18
        Duration: -736270.18:18:18.5510354
RepairResults: null
TestResults:
    MainOperation: Test
    Changes: []
    VerboseOutput: False
    VerboseErrors: False
    EndTime: 01.01.0001 00:00:00
    BeginTime: 03.11.2016 18:18:34
    Duration: -736270.18:18:34.2589293
VerboseOutput: False
VerboseErrors: False
EndTime: 01.01.0001 00:00:00
BeginTime: 03.11.2016 18:18:18
Duration: -736270.18:18:18.5510354
Messages: [
    No remote filesets were deleted
]
Warnings: [
    Metadata size is 139, but the largest accepted size is -1591738368, recording empty metadata,
    Metadata size is 137, but the largest accepted size is -1591738368, recording empty metadata,
    Metadata size is 137, but the largest accepted size is -1591738368, recording empty metadata,
    Metadata size is 137, but the largest accepted size is -1591738368, recording empty metadata
]
Errors: []
```
