### ISSUE TITLE
Arguments for scripts before/after options

### ISSUE THREAD

**Issue by mabeett** [duplicati/duplicati#2926]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.1-1
- **Operating system**: Ubuntu 16.04.3 LTS
- **Backend**: local filesystem

## Description

I need to call a script with arguments but when I call the task I get:

`ApplicationName='/home/foo/bar.sh jhon doe', CommandLine='', CurrentDirectory='', Native error= Cannot find the specified file`

## Steps to reproduce

1. Install duplicati
2. Configure a backup with the option `run-script-before-required`
3. Give to your scripts arguments

- **Actual result**:
The backup fails with this log `ApplicationName='/home/foo/bar.sh jhon doe', CommandLine='', CurrentDirectory='', Native error= Cannot find the specified file`
- **Expected result**:
The backup calls the script `'/home/foo/bar.sh` sending `jhon` and `doe' as arguments.

Thanks

**Comment by TheManchineel** [comment]
I guess a workaround is creating an extra script that calls the required one with an argument. Quite annoying that one has to do this.

**Comment by GeorgeGedox** [comment]
More than 3 years later and not even a label? This is a real issue that prevents flexible notification setups or even critical operations like stopping predefined services before a backup and so on, to take place. I really thing that this should be addressed.

**Comment by drwtsn32x** [comment]
I agree that this capability should be added for sure.  The workaround for the time being is to use a wrapper script.

**Comment by jbishop129** [comment]
This is an old one, but still a problem. Here's my use case if it helps:
I run Duplicati in a container, and use it to back up other containers. It's best practice to stop a container before backup, if it has a database or similar data, that would be inconsistent if backup is taken while running. 

To address this, I use `run-script-before-required` and `run-script-after`, calling to a bash script:
```
#!/bin/bash
docker stop container1 container2 container3 etc
```
This works fine, however the more correct way to do this, so I dont have to make a copy of this for every backup job, is to do:
```
#!/bin/bash
docker stop "$@"
```
With this, I can call the script with arguments like `./stop-containers.sh container1 container2 container3 etc`
and it'll stop the containers. Great! but, Duplicati doesn't seem to have a way to allow this in the config, so I'm back to duplicating/editing the script for each job.

P.S. For completeness, it's worth mentioning that in order for Duplicati running as a container to control the underlying Docker host, it needs the following to mounts passed:
```
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
```

**Comment by ezcafe** [comment]
@jbishop129 could you share the docker compose file please?
run-script-before and run-script-after don't work.
And docker_volumes is not access-able also

```
version: "2.1"
services:
  duplicati:
    image: linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=1000 # this should match the ouput of `id -u admin` on the CLI
      - PGID=1000 # this should match the ouput of `id -g admin` on the CLI
      - TZ=${TZ} # Set the appropriate timezone
      - CLI_ARGS=--run-script-before=./scripts/before.sh --run-script-after=./scripts/after.sh
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - duplicati_data:/config
      - /var/lib/docker/volumes:/docker_volumes:rw
    ports:
      - ${DUPLICATI_PORT}:8200
    restart: unless-stopped

volumes:
  duplicati_data: 
```
