### ISSUE TITLE
Non-existing paths on OneDrive cause internal server error when running Duplicati not on default port 8200

### ISSUE THREAD

**Issue by DMW007** [duplicati/duplicati#3006]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.1_beta_2017-08-01
- **Operating system**: Ubuntu 16.04.3 LTS as Docker-Container
- **Backend**: OneDrive (Personal)

## Description

I'm using the [Duplicati Docker image from linuxserver ](https://hub.docker.com/r/linuxserver/duplicati/) and found out some strang behavior, which seems related to target paths that doesn't exist. This only occurs when I redirect the default port 8200 of Duplicati to the default http port 80. I used traefik as reserse server here. This only occurs when I access the Web UI on port 80. Sadly, I can't get any debug output, altough I activated `debug-output` in the UI settings.

Using the default port 8200, all works fine. When I set a non existing target path, Duplicati asks me to create it for me. This isn't the case on port 80, here I only got an internal server error. 

### Summarized
**Works:**
- Port 80 with no target path
- Port 80 with a target path that already exists in OneDrive
- Port 8200 with existing/not existing/empty target path

**Doesn't work:**
- Port 80 with a target path that doesn't exists in OneDrive

## Steps to reproduce

1. Add a new backup using AES-256
2. Set the target to "Microsoft OneDrive" and specify a path on the server (e.g. /backups)
3. Request a token by clicking "AuthId" and confirm the connection to duplicati
4. Click "Test connection"

- **Actual result**:
Shows the error "Failed to connect: Internal Server Error"
- **Expected result**:
Establish a successfully connection

### docker-compose.yml
```
version: '2'
services:
  onedrive-backup:
    image: linuxserver/duplicati
    volumes:
      - ./config:/config
      - ./backup:/backup
      - ./source:/source
    networks:
      - nas-docker

#    ports:
#      - 8200:8200

    labels:
      - "traefik.port=8200"
      - "traefik.frontend.rule=my.host"
      - "traefik.frontend.entryPoints=http"
```

**Explanation**
Using the labels, I tell my reverse proxy traefik to look for port 8200 and forward traffic to it, when accessed on `my.host`. `traefik.frontend.entryPoints` set the entrypoint to http instead of https. This is required since I'm running a homeserver with some public services, where I want to use transport encryption using lets encrypt. However, I have some local services in my network like duplicati. Here lets encrypt is not possible, since it requires to access the domain from the internet. But that's another topic. Important is, that traefik acts like this: 

    [client] <--------http--------> [Traefik on port 80] <------http------> [Duplicati on port 8200]

The commented-out lines on `ports` are for direct port forwarding. If you comment them in, the port 8200 from the container would be mapped on port 8200 of the host. So you can access duplicati on $HostIp:8200 in the browser, like it would running directly on the host-machine.
