### ISSUE TITLE
Direct Restore from Backend Failing - Found X remote files that are not recorded in local storage, please run repair

### ISSUE THREAD

**Issue by kmwoley** [duplicati/duplicati#3231]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.3.3_beta_2018-04-02
- **Operating system**: Windows 10 (the machine doing the restore), Docker [linuxserver/duplicati] (the machine doing the backup)
- **Backend**: B2

## Description

While attempting a restore directly from the B2 backend from another machine than the one which performed the backup, I consistently get the error: 
`Found X remote files that are not recorded in local storage, please run repair`
Where `X` is the number of files I'm attempting to restore.

## Steps to reproduce

Unclear. The backup set is a 240.76 GB / 12 Versions backup set created 9 days ago.

- **Actual result**:
Error with no restored files.
```Found 3 remote files that are not recorded in local storage, please run repair```

- **Expected result**:
My files are restored.

## Debug log

This backup is quite large and it takes about an hour of the restore machine (Windows). When it throws this error, I don't see much in the logs on the Windows machine:

(note the "LastBackupDate" is suspicious)

**May 21, 2018 5:22 PM: Result**
```
MainOperation: Repair
RecreateDatabaseResults:
    MainOperation: Repair
    ParsedResult: Success
    EndTime: 5/21/2018 5:22:00 PM (1526948520)
    BeginTime: 5/21/2018 4:22:39 PM (1526944959)
    Duration: 00:59:21.0858338
    BackendStatistics:
        RemoteCalls: 4951
        BytesUploaded: 0
        BytesDownloaded: 267891406
        FilesUploaded: 0
        FilesDownloaded: 4950
        FilesDeleted: 0
        FoldersCreated: 0
        RetryAttempts: 0
        UnknownFileSize: 0
        UnknownFileCount: 0
        KnownFileCount: 0
        KnownFileSize: 0
        LastBackupDate: 1/1/0001 12:00:00 AM (-62135568000)
        BackupListCount: 0
        TotalQuotaSpace: 0
        FreeQuotaSpace: 0
        AssignedQuotaSpace: 0
        ReportedQuotaError: False
        ReportedQuotaWarning: False
        ParsedResult: Success
ParsedResult: Success
EndTime: 5/21/2018 5:22:01 PM (1526948521)
BeginTime: 5/21/2018 4:22:39 PM (1526944959)
Duration: 00:59:21.8094178
Messages: [
    Rebuild database started, downloading 11 filelists,
    Filelists restored, downloading 4939 index files,
    Recreate completed, verifying the database consistency,
    Recreate completed, and consistency checks completed, marking database as complete
]
Warnings: []
Errors: []
```
Kind of annoying that the log thinks it Succeeded. 👎 

**Running 'repair' on the backup machine (with the local DB) does not result in any change:**
```
Listing remote folder ...
Destination and database are synchronized, not making any changes
Return code: 0
```

**Running 'repair' directly on the backend storage:**
_In progress_: I'll report back once the `--dry-run` I'm running now completes.
