### ISSUE TITLE
VSS Error ID 8194 in Windows Event Viewer

### ISSUE THREAD

**Issue by Germs2004** [duplicati/duplicati#3236]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.3.3_beta_2018-04-02
- **Operating system**: Windows Server 2016
- **Backend**: A different local Windows Server 2016, shared folder

## Description
I run Duplicati as a Windows Service running as LocalSystem, and have snapshot-policy On and usn-policy On.  It seems to do successful backups and restores.  The Duplicati logs show no errors about VSS but there are errors in the Windows Event Viewer every time a Duplicati backup job runs.

Timeline:
```
Backup job started: 10:52:41
First error in Event Viewer: 10:52:46 AM
Second error in Event Viewer (duplicate of first): 10:59:15 AM
Begin time of Delete phase: 11:00:27 AM
Backup job End Time: 11:01:31 AM
```

Event Viewer error (2 of these):
```
Level = Error
Source = VSS
Event ID = 8194

Volume Shadow Copy Service error: Unexpected error querying for the IVssWriterCallback interface.  hr = 0x80070005, Access is denied.
. This is often caused by incorrect security settings in either the writer or requestor process. 

Operation:
   Gathering Writer Data

Context:
   Writer Class Id: {e8132975-6f93-4464-a53e-1050253ae220}
   Writer Name: System Writer
   Writer Instance ID: {2d2433ca-ba80-4d45-867b-aeebfb418c1e}
```

Duplicati backup job Result log:
```
DeletedFiles: 0
DeletedFolders: 0
ModifiedFiles: 2
ExaminedFiles: 280941
OpenedFiles: 2
AddedFiles: 0
SizeOfModifiedFiles: 73363456
SizeOfAddedFiles: 0
SizeOfExaminedFiles: 376658058583
SizeOfOpenedFiles: 73363456
NotProcessedFiles: 0
AddedFolders: 0
TooLargeFiles: 0
FilesWithError: 0
ModifiedFolders: 0
ModifiedSymlinks: 0
AddedSymlinks: 0
DeletedSymlinks: 0
PartialBackup: False
Dryrun: False
MainOperation: Backup
CompactResults:
    DeletedFileCount: 0
    DownloadedFileCount: 0
    UploadedFileCount: 0
    DeletedFileSize: 0
    DownloadedFileSize: 0
    UploadedFileSize: 0
    Dryrun: False
    MainOperation: Compact
    ParsedResult: Success
    EndTime: 5/25/2018 11:01:20 AM (1527260480)
    BeginTime: 5/25/2018 11:01:05 AM (1527260465)
    Duration: 00:00:14.9378394
    BackendStatistics:
        RemoteCalls: 9
        BytesUploaded: 31531335
        BytesDownloaded: 135107031
        FilesUploaded: 3
        FilesDownloaded: 3
        FilesDeleted: 1
        FoldersCreated: 0
        RetryAttempts: 0
        UnknownFileSize: 0
        UnknownFileCount: 0
        KnownFileCount: 4504
        KnownFileSize: 232152427832
        LastBackupDate: 5/25/2018 10:52:41 AM (1527259961)
        BackupListCount: 6
        TotalQuotaSpace: 12000539176960
        FreeQuotaSpace: 8154772398080
        AssignedQuotaSpace: -1
        ReportedQuotaError: False
        ReportedQuotaWarning: False
        ParsedResult: Success
DeleteResults:
    DeletedSets: [
        Item1: 1
        Item2: 5/25/2018 10:38:44 AM (1527259124)
    ]
    Dryrun: False
    MainOperation: Delete
    ParsedResult: Success
    EndTime: 5/25/2018 11:01:20 AM (1527260480)
    BeginTime: 5/25/2018 11:00:27 AM (1527260427)
    Duration: 00:00:53.2314182
RepairResults: null
TestResults:
    MainOperation: Test
    Verifications: [
        Key: duplicati-20180525T145241Z.dlist.zip.aes
        Value: [],
        Key: duplicati-i6b4a390ca4da402f9457d51dddd476e1.dindex.zip.aes
        Value: [],
        Key: duplicati-b7c8038aa788e44a28fa84ad204f92b2c.dblock.zip.aes
        Value: []
    ]
    ParsedResult: Success
    EndTime: 5/25/2018 11:01:31 AM (1527260491)
    BeginTime: 5/25/2018 11:01:28 AM (1527260488)
    Duration: 00:00:02.6094123
ParsedResult: Success
EndTime: 5/25/2018 11:01:31 AM (1527260491)
BeginTime: 5/25/2018 10:52:41 AM (1527259961)
Duration: 00:08:50.2555864
Messages: [
    [Retention Policy]: Start checking if backups can be removed,
    [Retention Policy]: Time frames and intervals pairs: 7.00:00:00 / 1.00:00:00, 28.00:00:00 / 7.00:00:00, 365.00:00:00 / 31.00:00:00,
    [Retention Policy]: Backups to consider: 5/25/2018 10:38:44 AM, 5/24/2018 2:21:24 PM, 5/10/2018 1:57:47 PM, 5/3/2018 1:00:47 PM, 3/23/2018 7:00:03 PM, 2/16/2018 5:27:37 PM,
    [Retention Policy]: Backups outside of all time frames and thus getting deleted: ,
    [Retention Policy]: All backups to delete: 5/25/2018 10:38:44 AM,
...
]
Warnings: []
Errors: []
```

## Steps to reproduce
1. Global setting "snapshot-policy" = On
2. Global setting "usn-policy" = On
3. Run a backup job
4. The backup job successfully finishes without any problems mentioned in the Duplicati logs.
5. Check the Windows Event Viewer and see the above mentioned errors.

- **Actual result**:
Several errors about VSS in the Windows Event Viewer

- **Expected result**:
No errors in the Windows Event Viewer.  If VSS problems occur, they should at least be logged in Duplicati's logs too.
