### ISSUE TITLE
Duplicati downloads too many files for one job

### ISSUE THREAD

**Issue by kerHbal** [duplicati/duplicati#3482]
- [x] I have searched open and closed issues for duplicates.
BUT there are so many topics that contain "download files", I tried best to find duplicates.
----------------------------------------

## Environment info
- **Duplicati version**: 2.0.3.3 beta
- **Operating system**: Window 10 1709
- **Backend**: Google Drive

## Description
Maybe related to this:
https://forum.duplicati.com/t/how-often-does-duplicati-test-your-backup-archives/216
 
This is a daily backup keeps running for months, and recently I didn't make big changes to the source files, and the advanced setting mentioned in the link above `--backup-test-samples` is set to default(1), so it should be just a notmal daily job.
But today I found it download more than 1GB. So I checked the log (the full version is at the end of the post)
```
Messages: [
    Deleting 2 remote fileset(s) ...,
    Deleted 2 remote fileset(s),
    Compacting because there is 25.69% wasted space and the limit is 25%,
    Downloaded 28 file(s) with a total size of 1.18 GB, deleted 56 file(s) with a total size of 1.18 GB, and compacted to 10 file(s) with a size of 240.37 MB, which reduced storage by 46 file(s) and 967.13 MB
]
```
Is there any reason for that? 
Thanks!

## Steps to reproduce
Not sure how to reproduce that.

## Debug log
```
DeletedFiles: 4
DeletedFolders: 0
ModifiedFiles: 26
ExaminedFiles: 24576
OpenedFiles: 47
AddedFiles: 21
SizeOfModifiedFiles: 256798229
SizeOfAddedFiles: 20802745
SizeOfExaminedFiles: 7287932562
SizeOfOpenedFiles: 277669899
NotProcessedFiles: 0
AddedFolders: 5
TooLargeFiles: 0
FilesWithError: 0
ModifiedFolders: 0
ModifiedSymlinks: 0
AddedSymlinks: 0
DeletedSymlinks: 0
PartialBackup: False
Dryrun: False
MainOperation: Backup
CompactResults:
    DeletedFileCount: 56
    DownloadedFileCount: 28
    UploadedFileCount: 10
    DeletedFileSize: 1266161976
    DownloadedFileSize: 1262739164
    UploadedFileSize: 252048459
    Dryrun: False
    MainOperation: Compact
    ParsedResult: Success
    EndTime: 2018/11/9 18:38:31 (1541806711)
    BeginTime: 2018/11/9 18:16:35 (1541805395)
    Duration: 00:21:56.2262357
    BackendStatistics:
        RemoteCalls: 104
        BytesUploaded: 303275673
        BytesDownloaded: 1315198771
        FilesUploaded: 13
        FilesDownloaded: 31
        FilesDeleted: 58
        FoldersCreated: 0
        RetryAttempts: 0
        UnknownFileSize: 0
        UnknownFileCount: 0
        KnownFileCount: 174
        KnownFileSize: 3957028822
        LastBackupDate: 2018/11/9 18:13:35 (1541805215)
        BackupListCount: 10
        TotalQuotaSpace: 109521666048
        FreeQuotaSpace: 64841295451
        AssignedQuotaSpace: -1
        ReportedQuotaError: False
        ReportedQuotaWarning: False
        ParsedResult: Success
DeleteResults:
    DeletedSets: [
        Item1: 1
        Item2: 2018/11/8 18:50:55 (1541721055),
        Item1: 7
        Item2: 2018/11/1 19:00:01 (1541113201)
    ]
    Dryrun: False
    MainOperation: Delete
    ParsedResult: Success
    EndTime: 2018/11/9 18:38:31 (1541806711)
    BeginTime: 2018/11/9 18:16:31 (1541805391)
    Duration: 00:21:59.8759134
RepairResults: null
TestResults:
    MainOperation: Test
    Verifications: [
        Key: duplicati-20181109T231335Z.dlist.zip.aes
        Value: [],
        Key: duplicati-i385849dfcef640719c160bdecdbb6c06.dindex.zip.aes
        Value: [],
        Key: duplicati-bb2194d0f46b54c6dae024e6683c95014.dblock.zip.aes
        Value: []
    ]
    ParsedResult: Success
    EndTime: 2018/11/9 18:39:20 (1541806760)
    BeginTime: 2018/11/9 18:38:36 (1541806716)
    Duration: 00:00:44.5344830
ParsedResult: Success
EndTime: 2018/11/9 18:39:21 (1541806761)
BeginTime: 2018/11/9 18:13:31 (1541805211)
Duration: 00:25:49.8003319
Messages: [
    Deleting 2 remote fileset(s) ...,
    Deleted 2 remote fileset(s),
    Compacting because there is 25.69% wasted space and the limit is 25%,
    Downloaded 28 file(s) with a total size of 1.18 GB, deleted 56 file(s) with a total size of 1.18 GB, and compacted to 10 file(s) with a size of 240.37 MB, which reduced storage by 46 file(s) and 967.13 MB
]
Warnings: []
Errors: []
```
