### ISSUE TITLE
Duplicati does not start up

### ISSUE THREAD

**Issue by roele** [duplicati/duplicati#3572]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.5_beta_2018-11-28
- **Operating system**: macOS 10.14.2
- **Backend**: local

## Description

Duplicati does not start up anymore.

## Steps to reproduce

1. Update mono via `brew-upgrade` to latest version (5.16.0.220)
2. Try to start Duplicati

Tried re-installing duplicati via brew (`brew cask uninstall duplicati && brew cask install duplicati`) with no effect.

- **Actual result**:
After clicking the Dupicati app nothing happens, no menu bar icon.
- **Expected result**:
Duplicati starts up and menu bar icon is visible.

## Debug log

[Duplicati-crashlog.txt](https://github.com/duplicati/duplicati/files/2717170/Duplicati-crashlog.txt)

**Comment by roele** [comment]
There are no related (Duplicati, mono) processes found in `ps -afe` and a restart does also not resolve the issue.

**Comment by rwoodpecker** [comment]
Experiencing the same issue.. mono version 5.18.0.225. Have tried reinstalling mono, reinstalling the latest duplicati beta and rebooting multiple times, but I end up with the same crash log as roele.

**Comment by DasenB** [comment]
I have the same problem with the same crash.

**Comment by DasenB** [comment]
I don't know how to fix this problem but as a workaround I decided to run Duplicati in a Docker until a real solution is found.

Here is the `docker-compose.yml` I am using:
``` 
duplicati:
    image: duplicati/duplicati
    restart: always
    volumes:
        - /Users/USERNAME/:/hostData
        - ./config:/data
    ports:
        - 127.0.0.1:8200:8200
```
