### ISSUE TITLE
Some subfolders not showing in backup source

### ISSUE THREAD

**Issue by eflemingtra** [duplicati/duplicati#3814]
- [ ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.23_beta_2019-07-14
- **Operating system**: Ubuntu Server 18.04 LTS 
- **Backend**: Docker

## Description

Duplicati is run in a container, started via Docker Compose. Duplicati starts and the interface is available a port 8200. When selecting backup source, multiple subfolders are missing and unfortunately are the ones I want to backup. For example /home is visible, but no subdirectories after home. Similarly, /media is visible but not the mounted drive at /media/externalusb.

Ironically, these folders are visible on another instance of Duplicati running on Windows 10 via the mounted network drive.

## Steps to reproduce

Below is my Docker Compose. I should note I have replaced the PUID and PGID with multiple different numbers (e.g., 1000 for my own user ID, 1 for root and 27 for sudo.  None change the problem). I have also changed folder permissions to multiple different options with no effect. Currently, my user folder is 755 and ownership is 1000/1000.

```
 duplicati:
    container_name: duplicati
    environment:
       - TZ=Australia/Sydney
       - PUID=1000
       - PGID=999  
    hostname: duplicati
    network_mode: host
    image: duplicati/duplicati
    ports:
       - 8200:8200
    privileged: true
    restart: unless-stopped
    volumes:
       - /home/efleming/docker/duplicati/config:/config
       - /home/efleming/docker/duplicati/data:/data/Duplicati
       - /home/efleming/docker/duplicatiBackups:/backups
       - /usr/local:/usr/local
       - /media:/source
       - /home/efleming:/source
       - /var/run/docker.sock:/var/run/docker.sock
       - /usr/bin/docker:/usr/bin/docker
```

## Screenshots

![image](https://user-images.githubusercontent.com/13082155/61202651-716e5800-a72b-11e9-8277-f52ef38b3eab.png)

## Debug log

No errors in logs
