### ISSUE TITLE
Duplicati will not display source files (HOME/...).

### ISSUE THREAD

**Issue by ignaciosala** [duplicati/duplicati#4322]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.1_beta_2020-01-18
- **Operating system**: Linux Ubuntu Version: 20.04.1 LTS
- **Backend**: Docker Version: 19.03.12

## Description

Duplicati will not show directory HOME/ignacio (where I store all the files I need to backup)
<img width="392" alt="Screen Shot 2020-09-19 at 7 54 26 PM" src="https://user-images.githubusercontent.com/69985807/93691419-d1d8f200-fab2-11ea-983d-7e4153d544dd.png">

## Steps to reproduce

I using the following docker stack,
```
version: "2.1"
services:
  duplicati:
    image: linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - CLI_ARGS= #optional
    volumes:
      - /home/ignacio/tig-stack/data/duplicati/config:/config
      - /home/ignacio/tig-stack/data/duplicati/backups:/backups
      - /home/ignacio/tig-stack/data:/source
    ports:
      - 8200:8200
    restart: unless-stopped
```

- **Actual result**:
/home/ignacio/tig-stack/data will not show when trying to select the source
- **Expected result**:
Being able to show these files so I can backup influxDB database
<img width="418" alt="Screen Shot 2020-09-19 at 8 07 50 PM" src="https://user-images.githubusercontent.com/69985807/93691489-d9e56180-fab3-11ea-9ee7-57678fcf39a9.png">

## Screenshots

<img width="332" alt="Screen Shot 2020-09-19 at 8 30 56 PM" src="https://user-images.githubusercontent.com/69985807/93691736-a99fc200-fab7-11ea-9de2-ae84163cf140.png">
<img width="557" alt="Screen Shot 2020-09-19 at 8 31 59 PM" src="https://user-images.githubusercontent.com/69985807/93691737-ad334900-fab7-11ea-8ffe-145df8a03459.png">
<img width="657" alt="Screen Shot 2020-09-19 at 8 33 58 PM" src="https://user-images.githubusercontent.com/69985807/93691739-b15f6680-fab7-11ea-9f24-5bd1e23257f1.png">

## Debug log

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 01-envfile: executing... ,
[cont-init.d] 01-envfile: exited 0.,
[cont-init.d] 10-adduser: executing... ,
,
-------------------------------------,
          _         (),
         | |  ___   _    __,
         | | / __| | |  /  \ ,
         | | \__ \ | | | () |,
         |_| |___/ |_|  \__/,
,
,
Brought to you by linuxserver.io,
-------------------------------------,
,
To support LSIO projects visit:,
https://www.linuxserver.io/donate/,
-------------------------------------,
GID/UID,
-------------------------------------,
,
User uid:    1000,
User gid:    1000,
-------------------------------------,
,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 30-config: executing... ,
[cont-init.d] 30-config: exited 0.,
[cont-init.d] 99-custom-scripts: executing... ,
[custom-init] no custom files found exiting...,
[cont-init.d] 99-custom-scripts: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,

```
