### ISSUE TITLE
IOException: Stale file handle

### ISSUE THREAD

**Issue by mfide** [duplicati/duplicati#5268]
Hello,

Thank you for this great tool. 

I started using duplicati almost a month ago to automate the backup requirements of my dedicated server in US .
The server runs Ubuntu **22.04** and Docker version **26.1.4** and below yml file represents my duplicati docker container usage. 
Currently it has Duplicati **v2.0.8.1_beta_2024-05-07**.
```
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=0 #uid of root user
      - PGID=0 #gid of the root group
      - TZ=Europe/Zurich
      - CLI_ARGS=
    volumes:
      - ./appdata/config:/config
      - /media/nas/Backups/Duplicati:/backups
      - /:/source
#    ports:
#      - 8200:8200
    restart: unless-stopped
```

In the host linux in US, I have an **NFS** mount `/media/nas/`, physically it is a 4TB SSD disk in my home (Switzerland)

My weekly backup tasks were working fine but I saw this morning that all tasks have been failed due to error called "IOException: Stale file handle". I thought that somehow I lost the NFS connection between my dedicated server in US and home nas but I verified it from the linux machine in US, the NFS mount is still active and working. (I can access to all files) So this was not the problem.

See below screenshot for the issue:
![duplicati_problem](https://github.com/user-attachments/assets/0da61071-1733-45c6-a589-a6f52049c306)

Later I decide to down the container of duplicati and up again and manually triggered the backup tasks and they all worked correctly.

Do you have any idea what can cause the "IOException: Stale file handle" error and later it disappears once I restart the duplicati?

Thank you.
