### ISSUE TITLE
Not able to make the Canary build run

### ISSUE THREAD

**Issue by pratbhoir** [duplicati/duplicati#6072]
- [ x] I have searched open and closed issues for duplicates.
- [ x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: v2.1.0.111_canary_2025-03-15
- **Operating system**: linux
- **Backend**: docker

## Description

I am trying to install the canary version of duplicati  build v2.1.0.111_canary_2025-03-15 in docker. But it is not also loading the initial screen.  
Things I tried.
1. stable version 2.1.0.5 from docker hub worked fine
2. verison 2.1.0.108-canary from docker hub worked fine
3. but 2.1.0.109-canary, 2.1.0.111-canary is not working.

## Steps to reproduce

1. Installed, docker version 2.1.0.5 from docker hub 
2. the screen was showing as loading... (I checked inspect element and found error in console saying. Uncaught TypeError: crypto.randomUUID is not a function
    at main-GMFQCDBZ.js:1:4956)
3. from url, I opened the http://192.168.0.32:9016/ngax/ page, It was saying (Connection to server was rejected due to invalid authentication.) 
4. Then I went to login page, and put the password it was giving error (Login failed: Failed to log in)

![Image](https://github.com/user-attachments/assets/c6829c00-bcca-45f7-b25a-bd92d41bd805)

![Image](https://github.com/user-attachments/assets/d66bde4b-3b2f-45a9-a161-9df0d45f8f28)

![Image](https://github.com/user-attachments/assets/0b7b41f6-d18d-4bf0-b46b-82ea6f2048f5)

- **Actual result**:
Replace me
- **Expected result**:
Replace me

## Screenshots

![Image](https://github.com/user-attachments/assets/50d4d479-fe6a-4f3e-bb3a-6b8202e140f5)

**Comment by pratbhoir** [comment]
Related to `crypto.randomUUID` issue, I tried on both the latest Edge and Chrome browsers, but it was not working.

After adding the below code to the compile main js, It worked but still gave an authentication issue.

I do not understand, the below docker-compose file worked fine when I passed 
` image: duplicati/duplicati:2.1.0.5`




Below is the docker-compose file used,


```
version: '3.9'

services:
  duplicati:
    container_name: Duplicati
    image: duplicati/duplicati:2.1.0.111-canary
    restart: unless-stopped
    network_mode: bridge
    hostname: Duplicati
    ports:
      - "9006:8200"
    environment:
      - DUPLICATI__WEBSERVICE_PASSWORD=Pass@123
      - PGID=1000
      - PUID=1000
      - SETTINGS_ENCRYPTION_KEY=f47ac10b-58cc-4e8e-9c32-293cbf2ac65c
      - TZ=Asia/Kolkata
    volumes:
      - /DATA/AppData:/appdata
      - /mnt/usbdrive/BackUp/Homelab:/backups
      - /DATA/AppData/Duplicati/data:/data
    deploy:
      resources:
        limits:
          memory: "7440695296"
        reservations:
          memory: "67108864"
    labels:
      icon: "https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Duplicati/icon.png"
```

**Comment by rattencreep** [comment]
I am having a similar issue upgrading from 2.1.0.109 to 2.1.0.111.
Changing the image from duplicati/duplicati:2.1.0.109 to duplicati/duplicati:2.1.0.111 results in the password being rejected. Reverting the image back resolves the issue.

docker compose used:

```dockerfile
---
networks:
  proxy:
    external: true

services:
  duplicati:
    image: duplicati/duplicati:2.1.0.111
    container_name: duplicati
    hostname: duplicati
    command: ["/opt/duplicati/duplicati-server", "--webservice-port=8200", "--webservice-interface=any", "--webservice-allowed-hostnames=*"]
    environment:
      SETTINGS_ENCRYPTION_KEY: 'somekey'
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/8200' || exit 1
      interval: 30s
      timeout: 15s
      retries: 3
    volumes:
      - /container_storage/duplicati:/data
      - /:/backup_source
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.duplicati.entrypoints=web, websecure"
      - "traefik.http.routers.duplicati.rule=Host(`sub.domain.tld`)"
      - "traefik.http.routers.duplicati.tls=true"
      - "traefik.http.routers.duplicati.tls.certresolver=production"
      - "traefik.http.routers.duplicati.middlewares=authentik@docker"
```

**Comment by marceloduplicati** [comment]
@kenkendk 

This is because `crypto.randomUUID` method is only available to pages served locally (localhost or 127.0.0.1) or over HTTPS.

I've made a quick test to confirm that on https://github.com/marceloduplicati/cryptorandomUUIDtest 

We could use https://www.npmjs.com/package/uuid either entirely or as a fallback method.

**Comment by jippi** [comment]
Can confirm `2.1.0.5` works for me, but not latest `canary` or released up to and including `2.1.0.111` - I'm accessing over HTTPS in both releases

**Comment by jeykodev** [comment]
@kenkendk / @marceloduplicati  any news on that topic? For home servers this is a show stopper, since most people accessing the service via internal IP without certificate.

**Comment by marceloduplicati** [comment]
@jeykodev I'll have a look at it.

**Comment by marceloduplicati** [comment]
@jeykodev I ran some tests to confirm, the issue was already [fixed](https://github.com/duplicati/ngclient/commit/a2d16cb588c3f0ae7ef7326f3f8350f1a8c73072), you can try it out with the latest Canary.

**Comment by jeykodev** [comment]
@marceloduplicati can confirm, its working! Thank you! :)

**Comment by Boldfor** [comment]
Jumping a bit late on the bandwagon. I'm running duplicati 2.2.0.1 on my Raspi via Docker. When trying to login (after the update to 2.2.0.1) I'm getting the following error...

<img width="470" height="363" alt="Image" src="https://github.com/user-attachments/assets/f76be2b6-10e6-4df9-9ef5-989326517f8b" />

... even though that's the password defined in my docker stack:

```
  duplicati:
    image: duplicati/duplicati
    container_name: duplicati
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Berlin
      - CLI_ARGS= #optional
      - DUPLICATI__WEBSERVICE_PASSWORD=${DUPLICATI_WEBSERVICE_PASSWORD}

    volumes:
      - /var/lib/docker/volumes/openhab_data_openhab_conf:/source/openhab_conf
      - /var/lib/docker/volumes/openhab_data_openhab_addons:/source/openhab_addons
      - /var/lib/docker/volumes/openhab_data_openhab_userdata:/source/openhab_userdata
      - /var/lib/docker/volumes/openhab_data_mosquitto_config:/source/mosquitto_config
      - /var/lib/docker/volumes/openhab_data_mosquitto_data:/source/mosquitto_data
      - /var/lib/docker/volumes/openhab_data_mosquitto_log:/source/mosquitto_log
      - /var/lib/docker/volumes/openhab_data_influxdb:/source/influxdb
      - /var/lib/docker/volumes/openhab_data_influxdb_config:/source/influxdb_config
      - /var/lib/docker/volumes/openhab_data_wmbusmeters_data:/source/wmbusmeters_data
      - /var/lib/docker/volumes/openhab_data_frigate_config:/source/frigate_config      
    ports:
      - 8200:8200
    restart: always
```

Does anyone have an idea?
